### ISSUE TITLE
`githooks install` command not recognized by CommandBox after Forgebox install

### ISSUE THREAD

**Issue by reginaldpark** [elpete/commandbox-githooks#6]
After installing commandbox-githooks from Forgebox I am not able to associate it with a git repo.  Getting the following error in CommandBox:
![image](https://user-images.githubusercontent.com/92599405/225369750-7e0882e9-abab-4f6b-a346-b18f6e8555d5.png)

**Comment by elpete** [comment]
Do you have a CommandBox alias for `git` set up?  That might be taking effect.  That error message means CommandBox is passing the command to the shell.

**Comment by reginaldpark** [comment]
That was it.  Thanks!  Is there a way to use githooks commands while having a git commandbox aliases?  I previously had the following git aliases setup that I thought was pretty nice: `config set command.aliases.git="!git"`

**Comment by reginaldpark** [comment]
Nevermind, I think I figured out a workaround.  Sorry about the fraudulent issue.
